version: '3.8'

services:
  spaceinvaders:
    image: digilize/spaceinvaders:latest
    container_name: spaceinvaders
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spaceinvaders.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.spaceinvaders.loadbalancer.server.port=80"
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - NGINX_VERSION=1.27.3
      - PKG_RELEASE=1
      - DYNPKG_RELEASE=1
      - NJS_VERSION=0.8.7
      - NJS_RELEASE=1
    expose:
      - "80"
    networks:
      - plesk-network

networks:
  plesk-network:
    external: true
    name: plesknetwork