version: '3.8'

services:
  space-invaders:
    image: digilize/spaceinvaders:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: space-invaders-3d
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web

networks:
  web:
    external: true
